### ISSUE TITLE
Unable to install on Windows

### ISSUE THREAD

**Issue by Malvoz** [w3c/i-slide#25]
`npm install` returns:

```cmd
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   win32
npm ERR! notsup Actual Arch: x64
```

**Comment by tidoust** [comment]
I'm not clear what conditions trigger that error. We got the same problem in the Github Action (which runs on Ubuntu) and fixed it by forcing the install of v7 of NPM:
https://github.com/w3c/i-slide/blob/main/.github/workflows/publish.yml#L28

I cannot reproduce that issue on my Windows computers (one runs npm v7.19.1 and Node.js v14.16.1, the other npm v7.23.0 and Node.js v16.9.0). Would you mind sharing the versions of Node.js and npm that you're using?

**Comment by Malvoz** [comment]
I was on a laptop with Node v12.14.0 and npm v6.13.4, with Node v14.17.6 and npm v7.24.1 I'm able to install without issues. Sorry for the noice.
